-- MySQL Script generated by MySQL Workbench
-- 07/03/14 15:46:37
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FIFA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FIFA` ;
CREATE SCHEMA IF NOT EXISTS `FIFA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `FIFA` ;

-- -----------------------------------------------------
-- Table `FIFA`.`Continente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Continente` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Continente` (
  `idContinente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idContinente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Pais` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Pais` (
  `idPais` INT NOT NULL,
  `nombre` VARCHAR(200) NULL,
  `bandera` VARCHAR(45) NULL,
  `idContinente` INT NULL,
  PRIMARY KEY (`idPais`),
  INDEX `idContinente_idx` (`idContinente` ASC),
  CONSTRAINT `idContinente`
    FOREIGN KEY (`idContinente`)
    REFERENCES `FIFA`.`Continente` (`idContinente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `idPais` INT NULL,
  `escudo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipo`),
  INDEX `idPais_idx` (`idPais` ASC),
  CONSTRAINT `idPais`
    FOREIGN KEY (`idPais`)
    REFERENCES `FIFA`.`Pais` (`idPais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`Integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Integrante` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Integrante` (
  `idIntegrante` INT NOT NULL,
  `nombre` VARCHAR(60) NULL,
  `edad` INT NULL,
  `peso` FLOAT NULL,
  `apellidos` VARCHAR(100) NULL,
  `idEquipo` INT NOT NULL,
  `estatura` FLOAT NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`idIntegrante`),
  INDEX `idEquipo_idx` (`idEquipo` ASC),
  CONSTRAINT `idEquipo`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `FIFA`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`Posicion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Posicion` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Posicion` (
  `idPosicion` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `abreviatura` VARCHAR(4) NULL,
  PRIMARY KEY (`idPosicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Jugador` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Jugador` (
  `idJugador` INT NOT NULL,
  `idPosicion` INT NOT NULL,
  `numero` INT NULL,
  INDEX `idPosicion_idx` (`idPosicion` ASC),
  INDEX `idJugador_idx` (`idJugador` ASC),
  CONSTRAINT `idPosicion`
    FOREIGN KEY (`idPosicion`)
    REFERENCES `FIFA`.`Posicion` (`idPosicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idJugador`
    FOREIGN KEY (`idJugador`)
    REFERENCES `FIFA`.`Integrante` (`idIntegrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`Estadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Estadio` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Estadio` (
  `idEstadio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Ciudad` VARCHAR(100) NULL,
  PRIMARY KEY (`idEstadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`Partido` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`Partido` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `equipoVisitante` INT NOT NULL,
  `equipoLocal` INT NOT NULL,
  `puntaje` VARCHAR(45) NULL,
  `idEstadio` INT NOT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `idEstadio_idx` (`idEstadio` ASC),
  INDEX `equipoLocal_idx` (`equipoLocal` ASC),
  INDEX `equipoVisitante_idx` (`equipoVisitante` ASC),
  CONSTRAINT `idEstadio`
    FOREIGN KEY (`idEstadio`)
    REFERENCES `FIFA`.`Estadio` (`idEstadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipoLocal`
    FOREIGN KEY (`equipoLocal`)
    REFERENCES `FIFA`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipoVisitante`
    FOREIGN KEY (`equipoVisitante`)
    REFERENCES `FIFA`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`tablaGoleoEquipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`tablaGoleoEquipo` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`tablaGoleoEquipo` (
  `idPartido` INT NOT NULL,
  `idEquipo` INT NOT NULL,
  `puntos` VARCHAR(45) NULL,
  INDEX `idEquipo_idx` (`idEquipo` ASC),
  INDEX `idPartido_idx` (`idPartido` ASC),
  CONSTRAINT `idEquipo`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `FIFA`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPartido`
    FOREIGN KEY (`idPartido`)
    REFERENCES `FIFA`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`tablaGoleoJugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`tablaGoleoJugador` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`tablaGoleoJugador` (
  `idPartido` INT NULL,
  `Goles` VARCHAR(45) NULL,
  `idJugador` INT NULL,
  `idtablaGoleoJugador` VARCHAR(45) NOT NULL,
  `minGol` TIME NULL,
  INDEX `idJugador_idx` (`idJugador` ASC),
  INDEX `idPartido_idx` (`idPartido` ASC),
  PRIMARY KEY (`idtablaGoleoJugador`),
  CONSTRAINT `idJugador`
    FOREIGN KEY (`idJugador`)
    REFERENCES `FIFA`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPartido`
    FOREIGN KEY (`idPartido`)
    REFERENCES `FIFA`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FIFA`.`tarjetasJugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FIFA`.`tarjetasJugador` ;

CREATE TABLE IF NOT EXISTS `FIFA`.`tarjetasJugador` (
  `idPartido` INT NOT NULL,
  `tipoTarjeta` VARCHAR(10) NULL,
  `idJugador` INT NOT NULL,
  `idTarjetaJugador` VARCHAR(45) NOT NULL,
  `minTarjeta` TIME NULL,
  INDEX `idJugador_idx` (`idJugador` ASC),
  INDEX `idPartido_idx` (`idPartido` ASC),
  PRIMARY KEY (`idTarjetaJugador`),
  CONSTRAINT `idJugador0`
    FOREIGN KEY (`idJugador`)
    REFERENCES `FIFA`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPartido0`
    FOREIGN KEY (`idPartido`)
    REFERENCES `FIFA`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
